<a href="https://colab.research.google.com/github/ishtarpcamo/ishtar/blob/main/Sola3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

سوال 3-1

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# بارگذاری دیتاست
data = pd.read_csv('/content/heart.csv')

# تقسیم داده‌ها به دو بخش آموزش و آزمون
train_data, test_data = train_test_split(data, test_size=0.15, random_state=42)

# نمایش تعداد ردیف‌های هر بخش
print("تعداد ردیف‌های بخش آموزش:", len(train_data))
print("تعداد ردیف‌های بخش آزمون:", len(test_data))

تعداد ردیف‌های بخش آموزش: 871
تعداد ردیف‌های بخش آزمون: 154


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# بارگذاری دیتاست
data = pd.read_csv('/content/heart.csv')

# تبدیل متغیرهای متنی به عددی
label_encoder = LabelEncoder()
data['target'] = label_encoder.fit_transform(data['target'])

# تقسیم داده‌ها به بخش‌های آموزش و آزمون
X = data.drop('target', axis=1)
y = data['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

# طراحی و آموزش درخت تصمیمی
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# پیش‌بینی برچسب‌ها برای داده‌های آزمون
y_pred = clf.predict(X_test)

# ارزیابی دقت مدل
accuracy = accuracy_score(y_test, y_pred)
print("دقت مدل:", accuracy)

# نمایش گزارش طبقه‌بندی
print(classification_report(y_test, y_pred))

دقت مدل: 0.9805194805194806
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        78
           1       1.00      0.96      0.98        76

    accuracy                           0.98       154
   macro avg       0.98      0.98      0.98       154
weighted avg       0.98      0.98      0.98       154



قسمت دوم سوال سوم

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.tree import DecisionTreeClassifier

# طراحی و آموزش درخت تصمیمی با فراپارامترهای مختلف
def train_decision_tree(max_depth, min_samples_split):
    clf = DecisionTreeClassifier(max_depth=max_depth, min_samples_split=min_samples_split)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    # ارزیابی با استفاده از ماتریس درهم‌ریختگی و شاخص‌های ارزیابی
    cm = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    return cm, accuracy, precision, recall

# ارزیابی با فراپارامترهای مختلف
max_depth_values = [3, 5, 7]
min_samples_split_values = [2, 5, 10]

for max_depth in max_depth_values:
    for min_samples_split in min_samples_split_values:
        cm, accuracy, precision, recall = train_decision_tree(max_depth, min_samples_split)
        print(f"Max Depth: {max_depth}, Min Samples Split: {min_samples_split}")
        print("Confusion Matrix:")
        print(cm)
        print("Accuracy:", accuracy)
        print("Precision:", precision)
        print("Recall:", recall)
        print("--------------------------------------------------")

Max Depth: 3, Min Samples Split: 2
Confusion Matrix:
[[53 25]
 [ 6 70]]
Accuracy: 0.7987012987012987
Precision: 0.7368421052631579
Recall: 0.9210526315789473
--------------------------------------------------
Max Depth: 3, Min Samples Split: 5
Confusion Matrix:
[[53 25]
 [ 6 70]]
Accuracy: 0.7987012987012987
Precision: 0.7368421052631579
Recall: 0.9210526315789473
--------------------------------------------------
Max Depth: 3, Min Samples Split: 10
Confusion Matrix:
[[53 25]
 [ 6 70]]
Accuracy: 0.7987012987012987
Precision: 0.7368421052631579
Recall: 0.9210526315789473
--------------------------------------------------
Max Depth: 5, Min Samples Split: 2
Confusion Matrix:
[[55 23]
 [ 3 73]]
Accuracy: 0.8311688311688312
Precision: 0.7604166666666666
Recall: 0.9605263157894737
--------------------------------------------------
Max Depth: 5, Min Samples Split: 5
Confusion Matrix:
[[55 23]
 [ 3 73]]
Accuracy: 0.8311688311688312
Precision: 0.7604166666666666
Recall: 0.9605263157894737
-----

**قسمت** سوم

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ایجاد یک مدل Random Forest با تعداد درخت‌های 100 و عمق درخت‌ها 10
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

# آموزش مدل
rf_model.fit(X_train, y_train)

# پیش‌بینی برای داده‌های آموزش و آزمون
train_pred = rf_model.predict(X_train)
test_pred = rf_model.predict(X_test)

# محاسبه دقت مدل
train_accuracy = accuracy_score(y_train, train_pred)
test_accuracy = accuracy_score(y_test, test_pred)

print(f"دقت مدل برای داده‌های آموزش: {train_accuracy}")
print(f"دقت مدل برای داده‌های آزمون: {test_accuracy}")

دقت مدل برای داده‌های آموزش: 1.0
دقت مدل برای داده‌های آزمون: 0.9805194805194806


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# تعریف مدل Random Forest
rf_model = RandomForestClassifier()

# تعیین فراپارامترهای مختلف برای GridSearch
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# ایجاد GridSearch با مدل و فراپارامترهای تعیین شده
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='accuracy')

# آموزش GridSearch بر روی داده‌های آموزش
grid_search.fit(X_train, y_train)

# بهترین فراپارامترها و دقت مدل به دست آمده
best_params = grid_search.best_params_
best_accuracy = grid_search.best_score_

print("بهترین فراپارامترها:")
print(best_params)
print("دقت مدل با بهترین فراپارامترها:")
print(best_accuracy)

بهترین فراپارامترها:
{'max_depth': 15, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
دقت مدل با بهترین فراپارامترها:
0.9942528735632183


سوال چهار

بارگیری داده‌ها و نمایش چند ردیف ابتدایی:

In [ ]:
import pandas as pd

data = pd.read_csv("drug200.csv")
print(data.head())

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY


تقسیم داده‌ها به بخش‌های آموزش و آزمون

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# خواندن داده از فایل CSV
data = pd.read_csv('/content/heart.csv')

# تقسیم داده‌ها به ویژگی‌ها (X) و برچسب‌ها (y)
X = data.drop('target', axis=1)
y = data['target']

# تقسیم داده‌ها به بخش‌های آموزش و آزمون
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# اعمال پیش‌پردازش مورد نیاز مانند مقیاس‌دهی داده‌ها
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ادامه بقیه مراحل و اجرای مدل
print("تعداد نمونه‌ها در بخش آموزش:", len(X_train))
print("تعداد نمونه‌ها در بخش آزمون:", len(X_test))

تعداد نمونه‌ها در بخش آموزش: 820
تعداد نمونه‌ها در بخش آزمون: 205


ماتریس
درهم ریختگی

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

# ایجاد مدل Naive Bayes
model = GaussianNB()

# آموزش مدل با داده‌های آموزش
model.fit(X_train_scaled, y_train)

# پیش‌بینی برچسب‌ها برای داده‌های آزمون
y_pred = model.predict(X_test_scaled)

# محاسبه ماتریس درهم‌ریختگی
conf_matrix = confusion_matrix(y_test, y_pred)
print("ماتریس درهم‌ریختگی:")
print(conf_matrix)

# تحلیل نتایج با استفاده از گزارش طبقه‌بندی
class_report = classification_report(y_test, y_pred)
print("گزارش طبقه‌بندی:")
print(class_report)

ماتریس درهم‌ریختگی:
[[72 30]
 [11 92]]
گزارش طبقه‌بندی:
              precision    recall  f1-score   support

           0       0.87      0.71      0.78       102
           1       0.75      0.89      0.82       103

    accuracy                           0.80       205
   macro avg       0.81      0.80      0.80       205
weighted avg       0.81      0.80      0.80       205



اعمال مدل طبقه‌بندی Bayes:


In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix

nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)
y_pred = nb_model.predict(X_test_scaled)

# تحلیل نتایج
print("ماتریس درهم ریختگی:")
print(confusion_matrix(y_test, y_pred))
print("\nگزارش طبقه‌بندی:")
print(classification_report(y_test, y_pred))

ماتریس درهم ریختگی:
[[57 21]
 [ 7 69]]

گزارش طبقه‌بندی:
              precision    recall  f1-score   support

           0       0.89      0.73      0.80        78
           1       0.77      0.91      0.83        76

    accuracy                           0.82       154
   macro avg       0.83      0.82      0.82       154
weighted avg       0.83      0.82      0.82       154



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

درنهایت، پنج داده را به صورت تصادفی از مجموعۀ آزمون انتخاب کنید و خروجی واقعی را با خروجی پیش بینی شده مقایسه
کنید.

In [ ]:
import numpy as np

# انتخاب پنج اندیس تصادفی از مجموعه آزمون
random_indices = np.random.choice(len(X_test), 5, replace=False)
random_X_test = X_test.iloc[random_indices]
random_y_test = y_test.iloc[random_indices]

# پیش‌بینی برچسب‌ها برای داده‌های انتخاب شده
random_y_pred = model.predict(random_X_test)

# مقایسه خروجی واقعی و پیش‌بینی شده
for i in range(5):
    print("داده شماره", i+1)
    print("خروجی واقعی:", random_y_test.iloc[i])
    print("خروجی پیش‌بینی شده:", random_y_pred[i])
    print("-----------------------")

داده شماره 1
خروجی واقعی: 0
خروجی پیش‌بینی شده: 0
-----------------------
داده شماره 2
خروجی واقعی: 0
خروجی پیش‌بینی شده: 0
-----------------------
داده شماره 3
خروجی واقعی: 1
خروجی پیش‌بینی شده: 0
-----------------------
داده شماره 4
خروجی واقعی: 1
خروجی پیش‌بینی شده: 0
-----------------------
داده شماره 5
خروجی واقعی: 1
خروجی پیش‌بینی شده: 0
-----------------------


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(
